### ISSUE TITLE
Unable to bind mount model path in tensorflow-serving zCX image

### ISSUE THREAD

**Issue by artem-minin** [IBM/ibm-z-oss-hub#37]
Following the instructions here: https://ibm.github.io/ibm-z-oss-hub/containers/tensorflow-serving.html.

 I have successfully pulled the icr.io/ibmz/tensorflow-serving:2.4.0 docker image into my local environment. Next, I copied the git repository https://github.com/tensorflow/serving to run an example. 

I am attempting to execute this step: 

docker run -t --rm -p 8501:8501 \
   -v "$TESTDATA/saved_model_half_plus_two_cpu:/models/half_plus_two" \
   -e MODEL_NAME=half_plus_two icr.io/ibmz/tensorflow-serving:2.4.0 &

However I get the following error: 

docker: Error response from daemon: authorization denied by plugin zcxauthplugin: Request to bind mount the path '/home/aaminin/serving-2.4.0-rc3/tensorflow_serving/servables/tensorflow/testdata/saved_model_half_plus_two_cpu' with rw mode is disabled for Docker running on IBM zCX appliance instance.

How do I get around this zCX issue to complete the provided example?

**Comment by artem-minin** [comment]
Work-Around: 
    1. docker pull [icr.io/ibmz/tensorflow-serving:2.4.0](http://icr.io/ibmz/tensorflow-serving:2.4.0)
    2. docker run -d  --name serving_base [icr.io/ibmz/tensorflow-serving:2.4.0](http://icr.io/ibmz/tensorflow-serving:2.4.0)
    3. docker cp /home/aaminin/serving-2.4.0-rc3/tensorflow_serving/servables/tensorflow/testdata/saved_model_half_plus_two_cpu serving_base:/models/half_plus_two
    4. docker commit --change "ENV MODEL_NAME half_plus_two” serving_base serving_test2
    5. docker kill serving_base
    6. docker run -t --rm -p 8501:8501 serving_test2 &:

Please test and update the instructions for the tensorflow-serving zCX image

**Comment by DebasishBlockchain** [comment]
The error you're encountering with zCX and Docker permissions is because zCX has certain security configurations that prevent Docker containers from performing certain actions. To work around this issue and complete the provided example, you can follow the Work-Around steps you've mentioned. However, I'll provide a more detailed explanation and some additional suggestions:

1. **Pull the Docker Image:**
   Pull the TensorFlow Serving image as you've done:

   ```bash
   docker pull icr.io/ibmz/tensorflow-serving:2.4.0
   ```

2. **Run a Base Container:**
   Create a base container to copy your model data into. This avoids the permission issues associated with bind mounts:

   ```bash
   docker run -d --name serving_base icr.io/ibmz/tensorflow-serving:2.4.0
   ```

3. **Copy Your Model Data:**
   Copy your model data into the base container. You can use the `docker cp` command as you've mentioned. Make sure to adjust the paths accordingly:

   ```bash
   docker cp /path/to/your/model_data serving_base:/models/half_plus_two
   ```

4. **Create a Custom Container:**
   Create a new custom container based on the base container. You can set the `MODEL_NAME` environment variable at this step as well:

   ```bash
   docker commit --change "ENV MODEL_NAME=half_plus_two" serving_base serving_custom
   ```

5. **Remove the Base Container:**
   You can now remove the base container:

   ```bash
   docker stop serving_base
   docker rm serving_base
   ```

6. **Run TensorFlow Serving Container:**
   Finally, start the TensorFlow Serving container using the custom image:

   ```bash
   docker run -t --rm -p 8501:8501 serving_custom
   ```

This should allow you to run TensorFlow Serving in your zCX environment without encountering the permission issues associated with bind mounts.

These steps essentially involve creating a custom Docker image that already contains your model data, which can be run without bind mounts, avoiding the permission issues you encountered.

**Comment by korpx-z** [comment]
@DebasishBlockchain Thank you!

I will look into this and update the run instructions immediately

**Comment by korpx-z** [comment]
instructions updated - thank you for your patience! (issues will be resolved at a much faster rate going onward.)
